[source.crates-io]
registry = "sparse+https://index.crates.io/"
# 指定镜像
replace-with = 'ustc' # 如：tuna、sjtu、ustc，或者 rustcc

# 注：以下源配置一个即可，无需全部
# 目前 sjtu 相对稳定些

# 字节跳动
[source.rsproxy]
registry = "sparse+https://rsproxy.cn/index/"

# 中国科学技术大学
[source.ustc]
registry = "sparse+https://mirrors.ustc.edu.cn/crates.io-index/"

# 上海交通大学
[source.sjtu]
registry = "sparse+https://mirrors.sjtug.sjtu.edu.cn/git/crates.io-index/"

# 清华大学
[source.tuna]
registry = "sparse+https://mirrors.tuna.tsinghua.edu.cn/git/crates.io-index/"

# 浙江大学
[source.zju]
registry = "sparse+https://mirrors.zju.edu.cn/crates.io-index/"

# 中国教育和科研计算机网
[source.cernet]
registry = "sparse+https://mirrors.cernet.edu.cn/crates.io-index/"

# rustcc社区
[source.rustcc]
registry = "sparse+https://code.aliyun.com/rustcc/crates.io-index/"
